/*==============================================================

                    BANKING SQL ANALYTICS PROJECT

Author      : Dhileep Kumar
Database    : PostgreSQL
File        : create_tables.sql

Description:
This script creates the relational database schema for a
banking loan management system. The schema consists of
10 normalized tables representing customers, loans,
products, branches, repayment schedules, collections,
loan officers, and NPA tracking.

==============================================================*/

--BRANCH MASTER--
CREATE TABLE BRANCH_MASTER(
	BRANCH_ID INT NOT NULL,
	BRANCH_NAME VARCHAR(100) NOT NULL,
	CITY VARCHAR(50) NOT NULL,
	STATE VARCHAR(50) NOT NULL,
	REGION VARCHAR(50) NOT NULL,
	CONSTRAINT PK_BRANCH PRIMARY KEY (BRANCH_ID)
);

--PRODUCT MASTER--
CREATE TABLE PRODUCT_MASTER(
	PRODUCTFLAG VARCHAR(20) NOT NULL,
	PRODUCT_NAME VARCHAR(50) NOT NULL,
	MIN_EFF DECIMAL(5,2) NOT NULL,
	MAX_EFF DECIMAL(5,2) NOT NULL,
	MAX_TENURE_MONTHS INT,
	PROCESSING_FEE_PCT DECIMAL(5,2),
	CONSTRAINT PK_PRODUCT PRIMARY KEY (PRODUCTFLAG)
);

--CUSTOMER MASTER--
CREATE TABLE CUSTOMER_MASTER(
	CIF_NO INT NOT NULL,
	CUSTOMERNAME VARCHAR(70) NOT NULL,
	DOB DATE,
	GENDER CHAR(1) CHECK(GENDER IN('M','F')),
	PAN_NO VARCHAR (10),
	MOBILE VARCHAR(10) CHECK(LENGTH(MOBILE) = 10),
	CITY VARCHAR(20),
	STATE VARCHAR (20),
	OCCUPATIONTYPE VARCHAR(50),
	MONTHLY_INCOME DECIMAL(10,2),
	CREDIT_SCORE INT CHECK(CREDIT_SCORE = -1 OR (CREDIT_SCORE BETWEEN 300 AND 900)),
	CUSTOMER_SINCE_DATE DATE NOT NULL,
	CONSTRAINT PK_CUSTOMER PRIMARY KEY (CIF_NO)
);

--LOAN_OFFICER_MASTER--
CREATE TABLE LOAN_OFFICER_MASTER(
	EMPID INT NOT NULL,
	EMP_NAME VARCHAR(50) NOT NULL,
	DESIGNATION VARCHAR(50),
	EXPERIENCE_YEARS INT,
	BRANCH_ID INT NOT NULL,
	DOJ DATE NOT NULL,
	CONSTRAINT PK_LOANOFFICER PRIMARY KEY (EMPID),
	CONSTRAINT FK_LOANOFFICER FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH_MASTER(BRANCH_ID)

);

--AGENT--
CREATE TABLE COLLECTION_AGENT_MASTER(
	AGENT_ID INT NOT NULL,
	AGENT_NAME VARCHAR (50) NOT NULL,
	EXPERIENCE_YEAR INT,
	BRANCH_ID INT NOT NULL,
	CONSTRAINT PK_AGENT PRIMARY KEY (AGENT_ID),
	CONSTRAINT FK_AGENT FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH_MASTER(BRANCH_ID)	
);



--LOAN MASTER--
CREATE TABLE LOAN_MASTER(
	LOAN_ID INT NOT NULL,
	CIF_NO INT NOT NULL,
	PRODUCTFLAG VARCHAR(20) NOT NULL,
	BRANCH_ID INT NOT NULL,
	EMPID INT NOT NULL,
	STATUS VARCHAR(10) CHECK (STATUS IN ('ACTIVE','CLOSED')),
	DISBURSAL_DATE DATE NOT NULL,
	EMI_END_DATE DATE NOT NULL,
	AMOUNT_FIN DECIMAL(15,2) NOT NULL CHECK(AMOUNT_FIN > 0),
	RATE_OF_INTEREST DECIMAL(5,2) CHECK(RATE_OF_INTEREST >= 0),
	DPD INT CHECK(DPD >= 0),
	EMI_OVERDUE INT,
	PRINCIPAL_OUTSTANDING DECIMAL(15,2) NOT NULL,
	CONSTRAINT PK_LOAN_MASTER PRIMARY KEY(LOAN_ID),
	CONSTRAINT FK_CIF_NO FOREIGN KEY(CIF_NO) REFERENCES CUSTOMER_MASTER(CIF_NO),
	CONSTRAINT FK_PRDFG FOREIGN KEY(PRODUCTFLAG) REFERENCES PRODUCT_MASTER(PRODUCTFLAG),
	CONSTRAINT FK_BH FOREIGN KEY(BRANCH_ID) REFERENCES BRANCH_MASTER(BRANCH_ID),
	CONSTRAINT FK_EMP FOREIGN KEY(EMPID) REFERENCES LOAN_OFFICER_MASTER(EMPID)
);


--REPAYMENT SCHEDULE--
CREATE TABLE REPAYMENT_SCHEDULE(
	SCHEDULE_ID INT NOT NULL,
	LOAN_ID INT NOT NULL,
	EMI_NO INT,
	DUE_DATE DATE,
	PRINCIPAL_COMP DECIMAL(15,2),
	INTEREST_COMP DECIMAL(15,2),
	OUTSTANDING_BAL DECIMAL(15,2) CHECK(OUTSTANDING_BAL >= 0),
	CONSTRAINT PK_SCHEDULE PRIMARY KEY(SCHEDULE_ID),
	CONSTRAINT FK_RS_LOAN FOREIGN KEY(LOAN_ID) REFERENCES LOAN_MASTER(LOAN_ID)
);

--REPAYMENT ACTUAL--
CREATE TABLE REPAYMENT_ACTUAL(
	RECEIPT_ID INT NOT NULL,
	LOAN_ID INT NOT NULL,
	EMI_NO INT,
	PAYMENT_DATE DATE,
	AMT_RECEIVED DECIMAL(15,2),
	PAYMENT_MODE VARCHAR(20) CHECK(PAYMENT_MODE IN ('CASH','UPI','NACH','CHEQUE','IMPS','NEFT')),
	CONSTRAINT PK_ACTUAL PRIMARY KEY(RECEIPT_ID),
	CONSTRAINT FK_RA_LOAN FOREIGN KEY(LOAN_ID) REFERENCES LOAN_MASTER(LOAN_ID)
);

--COLLECTION_DETAILS--
CREATE TABLE COLLECTION_DETAILS(
	COLLECTION_ID INT NOT NULL,
	LOAN_ID INT NOT NULL,
	BUCKET VARCHAR(10) CHECK(BUCKET IN ('0-30','30-60','60-90','90+')),
	AGENT_ID INT NOT NULL,
	RECOVERY_STATUS VARCHAR(50) CHECK (RECOVERY_STATUS IN('PENDING','PARTIAL','RECOVERED','WRITE_OFF')),
	RECOVERY_AMOUNT DECIMAL(15,2) CHECK(RECOVERY_AMOUNT >= 0),
	FOLLOWUP_DATE DATE,
	CONSTRAINT PK_COLLECTION PRIMARY KEY(COLLECTION_ID),
	CONSTRAINT FK_COLLECTION_LOAN FOREIGN KEY(LOAN_ID) REFERENCES LOAN_MASTER(LOAN_ID),
	CONSTRAINT FK_AGENT_ID FOREIGN KEY(AGENT_ID) REFERENCES COLLECTION_AGENT_MASTER(AGENT_ID)
	
);

--NPA TRACKING--
CREATE TABLE NPA_TRACKING(
	NPA_ID INT NOT NULL,
	LOAN_ID INT NOT NULL,
	AS_OF_DATE DATE,
	NPA_CATEGORY VARCHAR(10) CHECK(NPA_CATEGORY IN ('NPA','REGULAR','WRITE_OFF')),
	DPD_AS_OF_DATE INT,
	PROVISION_AMT DECIMAL(10,5),
	CONSTRAINT PK_NPA PRIMARY KEY(NPA_ID),
	CONSTRAINT FK_NPA_LOAN FOREIGN KEY(LOAN_ID) REFERENCES LOAN_MASTER(LOAN_ID)
);